import {Inter} from 'next/font/google'
import "./style.css";

const inter = Inter({
  weight:['400','700'],
  subsets:['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Top show info</h1>
        {children}
      </body>
    </html>
  );
}
